### ISSUE TITLE
Promote RJMOLD02 to RJM##?

### ISSUE THREAD

**Issue by csnxs** [Hypnotoad90/jmce#11]
I think RJMOLD02 is no longer shit enough to be classified as RJMOLD, should it be promoted to RJM?

Only issue would be records, but Mazter can move them... right?

**Comment by MazterQyou** [comment]
I can update the server if the WAD is patched, sure, but that's as far as it goes.

**Comment by Wirtualnosc** [comment]
Actually records on RJMOLD02 will have to be reset anyway due to a glitch that let you earn 2 helper points at once (which is patched now).

**Comment by csnxs** [comment]
👍 if in favour of the rename?
