### ISSUE TITLE
JPX50 - Crusher desyncs a little everytime you press the switch.

### ISSUE THREAD

**Issue by otaru1921** [Hypnotoad90/jmce#7]
Eventually it's impossible to clear it.

![image](https://cloud.githubusercontent.com/assets/6776230/14227700/dede5394-f8d9-11e5-857e-89b3045c7af4.png)

**Comment by otaru1921** [comment]
![image](https://cloud.githubusercontent.com/assets/6776230/14228443/6f7d001a-f8eb-11e5-856f-7beee013bbbd.png)

**Comment by Hypnotoad90** [comment]
Fixed
